import { describe, expect, it, vi } from 'vitest'
import { authMiddleware, generateToken, verifyToken } from '../src/config/jwt.js'

function createMockResponse() {
  const res = {}
  res.status = vi.fn().mockReturnValue(res)
  res.json = vi.fn().mockReturnValue(res)
  return res
}

describe('JWT config', () => {
  it('generateToken and verifyToken should be consistent', () => {
    const payload = { id: 101, email: 'jwt@example.com', username: 'jwt_user' }
    const token = generateToken(payload)
    const decoded = verifyToken(token)

    expect(typeof token).toBe('string')
    expect(decoded).toBeTruthy()
    expect(decoded.id).toBe(payload.id)
    expect(decoded.email).toBe(payload.email)
    expect(decoded.username).toBe(payload.username)
  })

  it('authMiddleware should accept token generated by generateToken', () => {
    const payload = { id: 202, email: 'middleware@example.com', username: 'middleware_user' }
    const token = generateToken(payload)
    const req = {
      headers: {
        authorization: `Bearer ${token}`
      }
    }
    const res = createMockResponse()
    const next = vi.fn()

    authMiddleware(req, res, next)

    expect(next).toHaveBeenCalledTimes(1)
    expect(req.user).toEqual({
      id: payload.id,
      email: payload.email,
      username: payload.username
    })
    expect(res.status).not.toHaveBeenCalled()
  })

  it('authMiddleware should return 401 for invalid token', () => {
    const req = {
      headers: {
        authorization: 'Bearer invalid_token'
      }
    }
    const res = createMockResponse()
    const next = vi.fn()

    authMiddleware(req, res, next)

    expect(next).not.toHaveBeenCalled()
    expect(res.status).toHaveBeenCalledWith(401)
    expect(res.json).toHaveBeenCalledWith(
      expect.objectContaining({
        success: false,
        code: 401
      })
    )
  })
})
